### ISSUE TITLE
No contact information

### ISSUE THREAD

**Issue by mehdicopter** [hacksalot/HackMyResume#153]
Hello,
Even if the json contains all contact informations, the output doesn't display it...
Does anyone else have this bug ?

**Comment by DreadPirateRob** [comment]
This is a little similar to issue 146. 
https://github.com/hacksalot/HackMyResume/issues/146

**Comment by hacksalot** [comment]
Should be resolved (if this is a builtin FRESH theme issue) in the next update. General rule is that the output is always determined by the theme. The theme presents a strongly opinionated view of the abstract resume model. Built-in FRESH themes have an additional (external) requirement: completeness. 100% coverage of the resume model. We're not there yet, hence the `-beta` designator on the themes repo, so this is a bug, albeit a sort of known one.

If OTOH you're talking about a JSON Resume theme, or a *custom* FRESH theme, then the output is always whatever the theme says it is. Easiest thing to do in that case is either find another theme, register an issue with the theme owner, or dupe the theme, make your edits, and use it in HMR with `-t`.

 @DreadPirateRob thanks! The move was smooth. *Recovering* from the move took a while.

**Comment by drkarl** [comment]
@hacksalot is it like the languages support for FRESH templates?

**Comment by ryneeverett** [comment]
Still seeing this in the dev branch using the modern fresh template. I see that there is in fact a contact section in the template so I'm kind of stumped.
