### ISSUE TITLE
Quotes get dousble-escaped

### ISSUE THREAD

**Issue by MOZGIII** [hacksalot/HackMyResume#199]
When using quotes (`"`) I get `&quot;` seen on the page and `&amp;quot;` in the page source (actual html).

When I use `resume-cli` with the same JSR themes it works correctly.

Sample input piece:
```json
{
  "work": [
    {
      "company": "OOO \"ABC\"",
      "position": "Employee",
      "website": "https://abc",
      "startDate": "2000-01-01",
      "highlights": []
    }
  ]
}
```

I am using theme `flat` and the format is JSR

**Comment by hacksalot** [comment]
Fixed in 1.9.0. Thanks for the report.

**Comment by anilanar** [comment]
@hacksalot 
After an `npm install hacksalot/hackmyresume#dev -g`, I still get double escaped single and double quotes. Is that expected?

**Comment by vidyu** [comment]
@anilanar If you use `-o "{noescape: true}"` the quotes are not double escaped.
@hacksalot the `--no-escape` option doesn't work though.
