### ISSUE TITLE
date rendering issue, get "@@@@~@@@@"

### ISSUE THREAD

**Issue by moribellamy** [hacksalot/HackMyResume#207]
To repro this issue I just made a github repo, https://github.com/moribellamy/sample-resume-issue.

I hooked it up to travis so that you could know exactly the environment i'm running stuff in. I expect the ./generate.sh script to generate a good looking resume, like this one: (see the dates are properly rendered): https://htmlpreview.github.io/?https://github.com/moribellamy/resume/blob/master/resume.html

However the actual code renders a bad looking resume (see the dates are wonky): https://htmlpreview.github.io/?https://github.com/moribellamy/sample-resume-issue/blob/master/resume.html.

Somehow it works on my local macbook pro though. The way I get the "good looking" resume is to `npm install -g hackmyresume`, so there must be some difference between my global install and my local, hermetic install. Here is my NPM package list: https://gist.github.com/moribellamy/90b7d1e932073d7be1526ab42e54071f

**Comment by hacksalot** [comment]
Thanks for the report and for putting together the reproducible test case. This is fixed in the latest code on `dev` and should be rolled into the 1.9.0 release, due in the next 48 hours or so.

**Comment by moribellamy** [comment]
NP, thanks for looking. I'm still seeing the issue at HEAD, I updated the reference repo. https://travis-ci.org/moribellamy/sample-resume-issue.

**Comment by hacksalot** [comment]
Try HEAD on the `dev` branch eg somewhere around 033b29fd3aa4a4b2e9eb6e49f22d4c12e1436028

**Comment by hacksalot** [comment]
Now fixed in the latest official release, v1.9.0-beta.
