### ISSUE TITLE
Applying JSON resume theme

### ISSUE THREAD

**Issue by umpirsky** [hacksalot/HackMyResume#56]
On http://please.hackmyresume.com/ it says "THEMES: CHOOSE FROM ANY FRESH OR JSON RESUME THEME OR"

I want to apply [slick](https://github.com/dfmcphee/jsonresume-theme-slick) theme.

What I tried so far:

```
$ npm install jsonresume-theme-slick

$ hackmyresume BUILD resume.json TO resume.html -t slick

*** HackMyResume v1.2.2 ***
Reading SOURCE resume: resume.json
ERROR: The specified theme couldn't be found: slick

$ hackmyresume BUILD resume.json TO resume.html -t node_modules/jsonresume-theme-slick/

*** HackMyResume v1.2.2 ***
Reading SOURCE resume: resume.json
ERROR: ENOENT, no such file or directory '/home/umpirsky/Projects/resume/node_modules/jsonresume-theme-slick/jsonresume-theme-slick.json'
```

What is the proper way to do it?

**Comment by hacksalot** [comment]
Hi @umpirsky thanks for the report. This should be fixed in v1.3. In the meantime as a workaround, you can use [resume-cli](https://github.com/jsonresume/resume-cli) but this entails an upload to the JRS Servers. I'll be back tonight at 9EST to work on this.

**Comment by umpirsky** [comment]
@hacksalot Thanks for quick answer. No problem, I will wait for v1.3, no rush. Thanks.

**Comment by xificurC** [comment]
Hi @hacksalot, any estimate on releasing that?
Thanks for this tool ;)

**Comment by hacksalot** [comment]
@xificurC Finishing it up tonight. Minor power outage here with the storm but we're back.

**Comment by xificurC** [comment]
@hacksalot I see, thanks for the update, I will be waiting :)

**Comment by pmbenjamin** [comment]
FYI - I wrote this [FAQ](https://github.com/hacksalot/HackMyResume/wiki/FAQ#themes). Hope it helps future users.

**Comment by hacksalot** [comment]
To use a JSON Resume theme locally with HackMyResume [v1.3.0](https://github.com/hacksalot/HackMyResume/releases/tag/v1.3.0):

1. Install the theme. I like use `npm install jsonresume-theme-[theme-name]`. You could also clone the theme's backing GH repo, or download it manually. NPM is easy and most/all JRS themes are on NPM. Note you don't need a package.json to pull down the theme.
2. Specify the relative path to the theme folder in the `-t` parameter:

        hackmyresume BUILD resume.json TO out/resume.all -t node_modules/jsonresume-theme-classy`

**Comment by herau** [comment]
nice ! thanks you @hacksalot

**Comment by caske33** [comment]
@hacksalot This creates 4 files: html, png, yml and json. But all contain the html file instead of the appropriate type.

Also no pdf is generated for JSR themes?

**Comment by umpirsky** [comment]
@hacksalot Tested, works. Awesome job, thanks!

**Comment by hacksalot** [comment]
@herau @umpirsky Thanks guys! @caske33 fixed in v1.3.1 (out shortly). Out of curiosity, does the HTML version display correctly?

**Comment by umpirsky** [comment]
@hacksalot Yes, I built with `jsonresume-theme-slick` and it looks great. Thanks. :+1:

**Comment by caske33** [comment]
@hacksalot I'm still getting the same output in all files (and no pdf)

And the html contains `@@@@~~@@@@` everywhere.

**Comment by herau** [comment]
@caske33 the html contains `@@@~~~@@@` when your JSON file contains empty entries.

**Comment by herau** [comment]
@hacksalot i have open an issue because i'm not able to generate a PDF with JSON-resume-theme #80

**Comment by hacksalot** [comment]
@caske33 @herau Should be fixed shortly. Will also add test coverage to verify resumes don't end up with any intermediary garbage like `@@@`. This should be logged as a separate issue. Thanks!
